export const EmojiList = {
  1: "https://be.linhug.com/emoji/1.png",
  2: "https://be.linhug.com/emoji/2.png",
  3: "https://be.linhug.com/emoji/3.png",
  4: "https://be.linhug.com/emoji/4.png",
  5: "https://be.linhug.com/emoji/5.png",
  6: "https://be.linhug.com/emoji/6.png",
  7: "https://be.linhug.com/emoji/7.png",
  8: "https://be.linhug.com/emoji/8.png",
  9: "https://be.linhug.com/emoji/9.png",
  10: "https://be.linhug.com/emoji/10.png",
  11: "https://be.linhug.com/emoji/11.png",
  12: "https://be.linhug.com/emoji/12.png",
  13: "https://be.linhug.com/emoji/13.png",
  14: "https://be.linhug.com/emoji/14.png",
  15: "https://be.linhug.com/emoji/15.png",
  16: "https://be.linhug.com/emoji/16.png",
  17: "https://be.linhug.com/emoji/17.png",
};

export const TextedEmojiList = {
  1: { emoji: "https://be.linhug.com/emoji/1.png", text: 'Sassy Room' },
  2: { emoji: "https://be.linhug.com/emoji/2.png", text: 'Laugh Room' },
  3: { emoji: "https://be.linhug.com/emoji/3.png", text: 'Big Smile Room' },
  4: { emoji: "https://be.linhug.com/emoji/4.png", text: 'Happy Room' },
  5: { emoji: "https://be.linhug.com/emoji/5.png", text: "Angel's Room" },
  6: { emoji: "https://be.linhug.com/emoji/6.png", text: "Love Room" },
  7: { emoji: "https://be.linhug.com/emoji/7.png", text: "Cool Room" },
  8: { emoji: "https://be.linhug.com/emoji/8.png", text: "Kiss Room" },
  9: { emoji: "https://be.linhug.com/emoji/9.png", text: 'Tired Room' },
  10: { emoji: "https://be.linhug.com/emoji/10.png", text: 'Scared Room' },
  11: { emoji: "https://be.linhug.com/emoji/11.png", text: 'Confused Room' },
  12: { emoji: "https://be.linhug.com/emoji/12.png", text: 'Emotional Room' },
  13: { emoji: "https://be.linhug.com/emoji/13.png", text: 'Sly Room' },
  14: { emoji: "https://be.linhug.com/emoji/14.png", text: 'Crazy Room' },
  15: { emoji: "https://be.linhug.com/emoji/15.png", text: 'Pedant Room' },
  16: { emoji: "https://be.linhug.com/emoji/16.png", text: 'Winners Room' },
  17: { emoji: "https://be.linhug.com/emoji/17.png", text: 'Cowboy Room' },
};