import { API_URL } from "constant/Varible";

export const EmojiList = {
  1: API_URL + "/emoji/1.png",
  2: API_URL + "/emoji/2.png",
  3: API_URL + "/emoji/3.png",
  4: API_URL + "/emoji/4.png",
  5: API_URL + "/emoji/5.png",
  6: API_URL + "/emoji/6.png",
  7: API_URL + "/emoji/7.png",
  8: API_URL + "/emoji/8.png",
  9: API_URL + "/emoji/9.png",
  10: API_URL + "/emoji/10.png",
  11: API_URL + "/emoji/11.png",
  12: API_URL + "/emoji/12.png",
  13: API_URL + "/emoji/13.png",
  14: API_URL + "/emoji/14.png",
  15: API_URL + "/emoji/15.png",
  16: API_URL + "/emoji/16.png",
  17: API_URL + "/emoji/17.png",
};

export const TextedEmojiList = {
  1: { emoji: API_URL + "/emoji/1.png", text: 'Sassy Room' },
  2: { emoji: API_URL + "/emoji/2.png", text: 'Laugh Room' },
  3: { emoji: API_URL + "/emoji/3.png", text: 'Big Smile Room' },
  4: { emoji: API_URL + "/emoji/4.png", text: 'Happy Room' },
  5: { emoji: API_URL + "/emoji/5.png", text: "Angel's Room" },
  6: { emoji: API_URL + "/emoji/6.png", text: "Love Room" },
  7: { emoji: API_URL + "/emoji/7.png", text: "Cool Room" },
  8: { emoji: API_URL + "/emoji/8.png", text: "Kiss Room" },
  9: { emoji: API_URL + "/emoji/9.png", text: 'Tired Room' },
  10: { emoji: API_URL + "/emoji/10.png", text: 'Scared Room' },
  11: { emoji: API_URL + "/emoji/11.png", text: 'Confused Room' },
  12: { emoji: API_URL + "/emoji/12.png", text: 'Emotional Room' },
  13: { emoji: API_URL + "/emoji/13.png", text: 'Sly Room' },
  14: { emoji: API_URL + "/emoji/14.png", text: 'Crazy Room' },
  15: { emoji: API_URL + "/emoji/15.png", text: 'Pedant Room' },
  16: { emoji: API_URL + "/emoji/16.png", text: 'Winners Room' },
  17: { emoji: API_URL + "/emoji/17.png", text: 'Cowboy Room' },
};