export const LANGUAGE_LIST = [
    { name: "Turkish", value: "tr" },
    { name: "Spanish", value: "es" },
    { name: "French", value: "fr" },
    { name: "Arabic", value: "ar" },
    { name: "Italian", value: "it" },
    { name: "German", value: "de" },
    { name: "Russian", value: "ru" },
    { name: "Indonesian", value: "id" },
    { name: "Filipino", value: "fil" },
    { name: "Hindi", value: "hi" },
    { name: "Swedish", value: "sv" },
    { name: "Japanese", value: "ja" },
    { name: "Korean", value: "ko" },
    { name: "Serbian", value: "sr" },
    { name: "Polish", value: "pl" },
    { name: "Malay", value: "ms" },
    { name: "Portuguese", value: "pt" },
    { name: "Romanian", value: "ro" },
    { name: "Thai", value: "th" },
];
