export const RoomList = [
  {
    id: "1",
    isStarted: false,
    roomAvatarId: 1,
    roomCode: "#343434",
    roomUserLength: 5,
    roomUserLimit: 8,
    roomName: "Cigi's Room",
  },
  {
    id: "2",
    isStarted: false,
    roomAvatarId: 2,
    roomCode: "#343434",
    roomUserLength: 5,
    roomUserLimit: 8,
    roomName: "Cigi's Room",
  },
  {
    id: "3",
    isStarted: false,
    roomAvatarId: 3,
    roomCode: "#343434",
    roomUserLength: 5,
    roomUserLimit: 8,
    roomName: "Cigi's Room",
  },
  {
    id: "4",
    isStarted: false,
    roomAvatarId: 4,
    roomCode: "#343434",
    roomUserLength: 5,
    roomUserLimit: 8,
    roomName: "Cigi's Room",
  },
  {
    id: "5",
    isStarted: false,
    roomAvatarId: 5,
    roomCode: "#343434",
    roomUserLength: 5,
    roomUserLimit: 8,
    roomName: "Cigi's Room",
  },
  {
    id: "6",
    isStarted: false,
    roomAvatarId: 6,
    roomCode: "#343434",
    roomUserLength: 5,
    roomUserLimit: 8,
    roomName: "Cigi's Room",
  },
];
